package com.tianruan.model;
// Generated Sep 21, 2016 9:21:18 AM by Hibernate Tools 5.1.0.Beta1

/**
 * RNoticePerson generated by hbm2java
 */
public class RNoticePerson implements java.io.Serializable {

	private String TNpId;
	private String TNoticeId;
	private String TPersonId;
	private String TRead;

	public RNoticePerson() {
	}

	public RNoticePerson(String TNpId) {
		this.TNpId = TNpId;
	}

	public RNoticePerson(String TNpId, String TNoticeId, String TPersonId, String TRead) {
		this.TNpId = TNpId;
		this.TNoticeId = TNoticeId;
		this.TPersonId = TPersonId;
		this.TRead = TRead;
	}

	public String getTNpId() {
		return this.TNpId;
	}

	public void setTNpId(String TNpId) {
		this.TNpId = TNpId;
	}

	public String getTNoticeId() {
		return this.TNoticeId;
	}

	public void setTNoticeId(String TNoticeId) {
		this.TNoticeId = TNoticeId;
	}

	public String getTPersonId() {
		return this.TPersonId;
	}

	public void setTPersonId(String TPersonId) {
		this.TPersonId = TPersonId;
	}

	public String getTRead() {
		return this.TRead;
	}

	public void setTRead(String TRead) {
		this.TRead = TRead;
	}

}
