package com.tianruan.model;
// Generated Sep 14, 2016 10:29:01 AM by Hibernate Tools 5.1.0.Beta1

/**
 * RRoleModule generated by hbm2java
 */
public class RRoleModule implements java.io.Serializable {

	private String TModuleId ;
	private String TRoleId ;
	
	public String getTModuleId() {
		return TModuleId;
	}
	public void setTModuleId(String tModuleId) {
		TModuleId = tModuleId;
	}
	public String getTRoleId() {
		return TRoleId;
	}
	public void setTRoleId(String tRoleId) {
		TRoleId = tRoleId;
	}

	

}
