package com.tianruan.model;
// Generated 2016-9-13 13:58:49 by Hibernate Tools 3.6.0.Final

/**
 * RUserRole generated by hbm2java
 */
public class RUserRole implements java.io.Serializable {

	private String TRoleId;
	private String TUserId;

	public RUserRole() {
	}

	public RUserRole(String TRoleId) {
		this.TRoleId = TRoleId;
	}

	public RUserRole(String TRoleId, String TUserId) {
		this.TRoleId = TRoleId;
		this.TUserId = TUserId;
	}

	public String getTRoleId() {
		return this.TRoleId;
	}

	public void setTRoleId(String TRoleId) {
		this.TRoleId = TRoleId;
	}

	public String getTUserId() {
		return this.TUserId;
	}

	public void setTUserId(String TUserId) {
		this.TUserId = TUserId;
	}

}
