package com.tianruan.model;
// Generated 2016-9-11 17:31:23 by Hibernate Tools 3.6.0.Final

/**
 * TDepartment generated by hbm2java
 */
public class TDepartment implements java.io.Serializable {

	private String TDeptId;
	private String TDeptName;
	private String TStatus;
	private String TBudget;
	private String TDeptDesc;
	private String TAdminId;
	private String TBianzhi;

	public TDepartment() {
	}

	public TDepartment(String TDeptId) {
		this.TDeptId = TDeptId;
	}

	public TDepartment(String TDeptId, String TDeptName, String TStatus, String TBudget, String TDeptDesc,
			String TAdminId, String TBianzhi) {
		this.TDeptId = TDeptId;
		this.TDeptName = TDeptName;
		this.TStatus = TStatus;
		this.TBudget = TBudget;
		this.TDeptDesc = TDeptDesc;
		this.TAdminId = TAdminId;
		this.TBianzhi = TBianzhi;
	}

	public String getTDeptId() {
		return this.TDeptId;
	}

	public void setTDeptId(String TDeptId) {
		this.TDeptId = TDeptId;
	}

	public String getTDeptName() {
		return this.TDeptName;
	}

	public void setTDeptName(String TDeptName) {
		this.TDeptName = TDeptName;
	}

	public String getTStatus() {
		return this.TStatus;
	}

	public void setTStatus(String TStatus) {
		this.TStatus = TStatus;
	}

	public String getTBudget() {
		return this.TBudget;
	}

	public void setTBudget(String TBudget) {
		this.TBudget = TBudget;
	}

	public String getTDeptDesc() {
		return this.TDeptDesc;
	}

	public void setTDeptDesc(String TDeptDesc) {
		this.TDeptDesc = TDeptDesc;
	}

	public String getTAdminId() {
		return this.TAdminId;
	}

	public void setTAdminId(String TAdminId) {
		this.TAdminId = TAdminId;
	}

	public String getTBianzhi() {
		return this.TBianzhi;
	}

	public void setTBianzhi(String TBianzhi) {
		this.TBianzhi = TBianzhi;
	}

}
