package com.tianruan.model;
// Generated 2016-9-29 21:06:37 by Hibernate Tools 3.6.0.Final

/**
 * TLeavePermit generated by hbm2java
 */
public class TLeavePermit implements java.io.Serializable {

	private String TLpId;
	private String TLpType;
	private String TStartTime;
	private String TEndTime;
	private String TStatus;
	private String TPersonId;
	private String TAdminId;

	public TLeavePermit() {
	}

	public TLeavePermit(String TLpId, String TPersonId) {
		this.TLpId = TLpId;
		this.TPersonId = TPersonId;
	}

	public TLeavePermit(String TLpId, String TLpType, String TStartTime, String TEndTime, String TStatus,
			String TPersonId, String TAdminId) {
		this.TLpId = TLpId;
		this.TLpType = TLpType;
		this.TStartTime = TStartTime;
		this.TEndTime = TEndTime;
		this.TStatus = TStatus;
		this.TPersonId = TPersonId;
		this.TAdminId = TAdminId;
	}

	public String getTLpId() {
		return this.TLpId;
	}

	public void setTLpId(String TLpId) {
		this.TLpId = TLpId;
	}

	public String getTLpType() {
		return this.TLpType;
	}

	public void setTLpType(String TLpType) {
		this.TLpType = TLpType;
	}

	public String getTStartTime() {
		return this.TStartTime;
	}

	public void setTStartTime(String TStartTime) {
		this.TStartTime = TStartTime;
	}

	public String getTEndTime() {
		return this.TEndTime;
	}

	public void setTEndTime(String TEndTime) {
		this.TEndTime = TEndTime;
	}

	public String getTStatus() {
		return this.TStatus;
	}

	public void setTStatus(String TStatus) {
		this.TStatus = TStatus;
	}

	public String getTPersonId() {
		return this.TPersonId;
	}

	public void setTPersonId(String TPersonId) {
		this.TPersonId = TPersonId;
	}

	public String getTAdminId() {
		return this.TAdminId;
	}

	public void setTAdminId(String TAdminId) {
		this.TAdminId = TAdminId;
	}

}
