package com.tianruan.model;
// Generated 2016-9-6 16:24:50 by Hibernate Tools 3.6.0.Final

/**
 * TModules generated by hbm2java
 */
public class TModules implements java.io.Serializable {

	private String TModuleId;
	private String TModuleName;
	private String TModulePid;
	private String TModuleUrl;

	public TModules() {
	}

	public TModules(String TModuleId) {
		this.TModuleId = TModuleId;
	}

	public TModules(String TModuleId, String TModuleName, String TModulePid, String TModuleUrl) {
		this.TModuleId = TModuleId;
		this.TModuleName = TModuleName;
		this.TModulePid = TModulePid;
		this.TModuleUrl = TModuleUrl;
	}

	public String getTModuleId() {
		return this.TModuleId;
	}

	public void setTModuleId(String TModuleId) {
		this.TModuleId = TModuleId;
	}

	public String getTModuleName() {
		return this.TModuleName;
	}

	public void setTModuleName(String TModuleName) {
		this.TModuleName = TModuleName;
	}

	public String getTModulePid() {
		return this.TModulePid;
	}

	public void setTModulePid(String TModulePid) {
		this.TModulePid = TModulePid;
	}

	public String getTModuleUrl() {
		return this.TModuleUrl;
	}

	public void setTModuleUrl(String TModuleUrl) {
		this.TModuleUrl = TModuleUrl;
	}

}
