package com.tianruan.model;
// Generated 2016-9-11 21:37:24 by Hibernate Tools 3.6.0.Final

/**
 * TNotice generated by hbm2java
 */
public class TNotice implements java.io.Serializable {

	private String TNoticeId;
	private String TTitle;
	private String TContent;
	private String TAdminId;
	private String TAddDate;
	private String TStatus;
	private String TVisitNum;

	public TNotice() {
	}

	public TNotice(String TNoticeId) {
		this.TNoticeId = TNoticeId;
	}

	public TNotice(String TNoticeId, String TTitle, String TContent, String TAdminId, String TAddDate, String TStatus,
			String TVisitNum) {
		this.TNoticeId = TNoticeId;
		this.TTitle = TTitle;
		this.TContent = TContent;
		this.TAdminId = TAdminId;
		this.TAddDate = TAddDate;
		this.TStatus = TStatus;
		this.TVisitNum = TVisitNum;
	}

	public String getTNoticeId() {
		return this.TNoticeId;
	}

	public void setTNoticeId(String TNoticeId) {
		this.TNoticeId = TNoticeId;
	}

	public String getTTitle() {
		return this.TTitle;
	}

	public void setTTitle(String TTitle) {
		this.TTitle = TTitle;
	}

	public String getTContent() {
		return this.TContent;
	}

	public void setTContent(String TContent) {
		this.TContent = TContent;
	}

	public String getTAdminId() {
		return this.TAdminId;
	}

	public void setTAdminId(String TAdminId) {
		this.TAdminId = TAdminId;
	}

	public String getTAddDate() {
		return this.TAddDate;
	}

	public void setTAddDate(String TAddDate) {
		this.TAddDate = TAddDate;
	}

	public String getTStatus() {
		return this.TStatus;
	}

	public void setTStatus(String TStatus) {
		this.TStatus = TStatus;
	}

	public String getTVisitNum() {
		return this.TVisitNum;
	}

	public void setTVisitNum(String TVisitNum) {
		this.TVisitNum = TVisitNum;
	}

}
