package com.tianruan.model;
// Generated 2016-9-6 16:24:50 by Hibernate Tools 3.6.0.Final

/**
 * TPerson generated by hbm2java
 */
public class TPerson implements java.io.Serializable {

	private String TPersonId;
	private String TPersonName;
	private String TMobile;
	private String TWorkNum;
	private String TEducation;
	private String TIdNum;
	private String TAddress;
	private String TGender;
	private String TBirthDate;
	private String TAddDate;
	private String TWorkPhone;
	private String TType;
	private String TJobId;
	private String TDepartmentId;

	public TPerson() {
	}

	public TPerson(String TPersonId, String TJobId, String TDepartmentId) {
		this.TPersonId = TPersonId;
		this.TJobId = TJobId;
		this.TDepartmentId = TDepartmentId;
	}

	public TPerson(String TPersonId, String TPersonName, String TMobile, String TWorkNum, String TEducation,
			String TIdNum, String TAddress, String TGender, String TBirthDate, String TAddDate, String TWorkPhone,
			String TType, String TJobId, String TDepartmentId) {
		this.TPersonId = TPersonId;
		this.TPersonName = TPersonName;
		this.TMobile = TMobile;
		this.TWorkNum = TWorkNum;
		this.TEducation = TEducation;
		this.TIdNum = TIdNum;
		this.TAddress = TAddress;
		this.TGender = TGender;
		this.TBirthDate = TBirthDate;
		this.TAddDate = TAddDate;
		this.TWorkPhone = TWorkPhone;
		this.TType = TType;
		this.TJobId = TJobId;
		this.TDepartmentId = TDepartmentId;
	}

	public String getTPersonId() {
		return this.TPersonId;
	}

	public void setTPersonId(String TPersonId) {
		this.TPersonId = TPersonId;
	}

	public String getTPersonName() {
		return this.TPersonName;
	}

	public void setTPersonName(String TPersonName) {
		this.TPersonName = TPersonName;
	}

	public String getTMobile() {
		return this.TMobile;
	}

	public void setTMobile(String TMobile) {
		this.TMobile = TMobile;
	}

	public String getTWorkNum() {
		return this.TWorkNum;
	}

	public void setTWorkNum(String TWorkNum) {
		this.TWorkNum = TWorkNum;
	}

	public String getTEducation() {
		return this.TEducation;
	}

	public void setTEducation(String TEducation) {
		this.TEducation = TEducation;
	}

	public String getTIdNum() {
		return this.TIdNum;
	}

	public void setTIdNum(String TIdNum) {
		this.TIdNum = TIdNum;
	}

	public String getTAddress() {
		return this.TAddress;
	}

	public void setTAddress(String TAddress) {
		this.TAddress = TAddress;
	}

	public String getTGender() {
		return this.TGender;
	}

	public void setTGender(String TGender) {
		this.TGender = TGender;
	}

	public String getTBirthDate() {
		return this.TBirthDate;
	}

	public void setTBirthDate(String TBirthDate) {
		this.TBirthDate = TBirthDate;
	}

	public String getTAddDate() {
		return this.TAddDate;
	}

	public void setTAddDate(String TAddDate) {
		this.TAddDate = TAddDate;
	}

	public String getTWorkPhone() {
		return this.TWorkPhone;
	}

	public void setTWorkPhone(String TWorkPhone) {
		this.TWorkPhone = TWorkPhone;
	}

	public String getTType() {
		return this.TType;
	}

	public void setTType(String TType) {
		this.TType = TType;
	}

	public String getTJobId() {
		return this.TJobId;
	}

	public void setTJobId(String TJobId) {
		this.TJobId = TJobId;
	}

	public String getTDepartmentId() {
		return this.TDepartmentId;
	}

	public void setTDepartmentId(String TDepartmentId) {
		this.TDepartmentId = TDepartmentId;
	}

}
