package com.tianruan.model;
// Generated 2016-9-7 20:53:40 by Hibernate Tools 3.6.0.Final

/**
 * TRole generated by hbm2java
 */
public class TRole implements java.io.Serializable {

	private String TRoleId;
	private String TRoleName;

	public TRole() {
	}

	public TRole(String TRoleId) {
		this.TRoleId = TRoleId;
	}

	public TRole(String TRoleId, String TRoleName) {
		this.TRoleId = TRoleId;
		this.TRoleName = TRoleName;
	}

	public String getTRoleId() {
		return this.TRoleId;
	}

	public void setTRoleId(String TRoleId) {
		this.TRoleId = TRoleId;
	}

	public String getTRoleName() {
		return this.TRoleName;
	}

	public void setTRoleName(String TRoleName) {
		this.TRoleName = TRoleName;
	}

}
