package com.tianruan.model;
// Generated 2016-9-25 23:15:29 by Hibernate Tools 3.6.0.Final

/**
 * TWorkRules generated by hbm2java
 */
public class TWorkRules implements java.io.Serializable {

	private String TRuleId;
	private String TStartTime;
	private String TEndTime;
	private String TAfterMinute;

	public TWorkRules() {
	}

	public TWorkRules(String TRuleId) {
		this.TRuleId = TRuleId;
	}

	public TWorkRules(String TRuleId, String TStartTime, String TEndTime, String TAfterMinite) {
		this.TRuleId = TRuleId;
		this.TStartTime = TStartTime;
		this.TEndTime = TEndTime;
		this.TAfterMinute = TAfterMinite;
	}

	public String getTRuleId() {
		return this.TRuleId;
	}

	public void setTRuleId(String TRuleId) {
		this.TRuleId = TRuleId;
	}

	public String getTStartTime() {
		return this.TStartTime;
	}

	public void setTStartTime(String TStartTime) {
		this.TStartTime = TStartTime;
	}

	public String getTEndTime() {
		return this.TEndTime;
	}

	public void setTEndTime(String TEndTime) {
		this.TEndTime = TEndTime;
	}

	public String getTAfterMinute() {
		return this.TAfterMinute;
	}

	public void setTAfterMinute(String TAfterMinute) {
		this.TAfterMinute = TAfterMinute;
	}

}
